// Landing-page default copy (AR/EN). The owner can override any of these
// from the dashboard; saved values are merged over these defaults.
export const LANDING_COPY = {
  ar: {
    nav: { features: 'المميزات', how: 'الطريقة', showcase: 'أمثلة', pricing: 'الأسعار', faq: 'الأسئلة' },
    cta: 'ابدأ الآن',
    login: 'دخول',
    heroEyebrow: 'منصة بورتفوليو متعدّدة المستخدمين',
    heroTitle: 'بورتفوليو احترافي،',
    heroTitleAccent: 'في دقائق.',
    heroSub:
      'اعرض مشاريعك وريلزك ومقالاتك في موقع سريع ومتجاوب — بالعربي والإنجليزي، على دومينك الخاص، من غير كود.',
    heroBtn1: 'اطلب بورتفوليو',
    heroBtn2: 'شوف مثال حي',
    featuresTitle: 'كل اللي تحتاجه في مكان واحد',
    features: [
      { icon: '🎨', t: 'تصميم قابل للتخصيص', d: 'ألوان وخطوط وأقسام قابلة للترتيب من لوحة تحكم عربية بالكامل.' },
      { icon: '🖼️', t: 'مشاريع وريلز', d: 'شبكات صور، عارض ريلز عمودي 9:16، ستوري هايلايتس، وصفحات تفاصيل للمشاريع.' },
      { icon: '✍️', t: 'مدوّنة ومقالات', d: 'محرّر غني + HTML خام، مع SEO و JSON-LD لكل مقال.' },
      { icon: '🌐', t: 'دومينك الخاص', d: 'اربط دومينك بضغطة، مع شهادة SSL تلقائية.' },
      { icon: '⚡', t: 'سريع و SEO', d: 'صور WebP، Sitemap، بيانات منظّمة، وتحميل كسول للأداء.' },
      { icon: '📩', t: 'نموذج تواصل شغّال', d: 'رسائل العملاء توصلك على إيميلك مباشرة، مع صفحة آراء عامة.' },
    ],
    howTitle: 'ثلاث خطوات وخلاص',
    how: [
      { n: '1', t: 'سجّل دخولك', d: 'ادخل لوحة التحكم وابدأ من قالب جاهز.' },
      { n: '2', t: 'ضيف محتواك', d: 'ارفع مشاريعك وصورك ومقالاتك ورتّب الأقسام.' },
      { n: '3', t: 'انشر', d: 'اربط دومينك وشارك موقعك مع العالم.' },
    ],
    showcaseTitle: 'بورتفوليوهات حيّة على المنصة',
    showcaseEmpty: 'قريباً — أول البورتفوليوهات في الطريق.',
    visit: 'زيارة',
    pricingTitle: 'أسعار بسيطة',
    plans: [
      { name: 'مجاني', price: '0', per: 'للأبد', feats: ['بورتفوليو واحد', 'رابط ViralPX', 'مشاريع ومقالات', 'مساحة 1GB'], cta: 'ابدأ مجاناً', hi: false },
      { name: 'برو', price: '199', per: 'شهرياً', feats: ['دومينك الخاص + SSL', 'مساحة أكبر', 'إزالة العلامة', 'أولوية الدعم'], cta: 'اشترك في برو', hi: true },
    ],
    faqTitle: 'أسئلة شائعة',
    faqs: [
      { q: 'محتاج أعرف كود؟', a: 'لأ خالص. كل حاجة من لوحة تحكم عربية بالسحب والإفلات.' },
      { q: 'أقدر أربط دوميني؟', a: 'أيوه، في خطة برو تربط دومينك بشهادة SSL تلقائية.' },
      { q: 'الموقع بيدعم العربي والإنجليزي؟', a: 'أيوه، ثنائي اللغة مع دعم كامل للاتجاه من اليمين لليسار.' },
      { q: 'بياناتي في أمان؟', a: 'كل مستخدم معزول تماماً عن غيره، والصور على CDN آمن.' },
    ],
    ctaTitle: 'جاهز تطلق بورتفوليوك؟',
    ctaSub: 'ابدأ دلوقتي — أول بورتفوليو مجاني.',
    ctaBtn: 'ابدأ الآن',
    rights: 'كل الحقوق محفوظة',
  },
  en: {
    nav: { features: 'Features', how: 'How it works', showcase: 'Showcase', pricing: 'Pricing', faq: 'FAQ' },
    cta: 'Get started',
    login: 'Log in',
    heroEyebrow: 'Multi-tenant portfolio platform',
    heroTitle: 'A professional portfolio,',
    heroTitleAccent: 'in minutes.',
    heroSub:
      'Show your projects, reels and articles on a fast, responsive site — Arabic & English, on your own domain, no code.',
    heroBtn1: 'Request a portfolio',
    heroBtn2: 'See a live example',
    featuresTitle: 'Everything you need, in one place',
    features: [
      { icon: '🎨', t: 'Customizable design', d: 'Colors, fonts and reorderable sections from a full dashboard.' },
      { icon: '🖼️', t: 'Projects & reels', d: 'Image grids, a 9:16 vertical reels player, story highlights and project pages.' },
      { icon: '✍️', t: 'Blog & articles', d: 'Rich editor + raw HTML, with SEO and JSON-LD per article.' },
      { icon: '🌐', t: 'Your own domain', d: 'Connect your domain in a click, with automatic SSL.' },
      { icon: '⚡', t: 'Fast & SEO-ready', d: 'WebP images, sitemap, structured data and lazy loading.' },
      { icon: '📩', t: 'Working contact form', d: 'Client messages reach your inbox, plus a public reviews page.' },
    ],
    howTitle: 'Three steps, done',
    how: [
      { n: '1', t: 'Log in', d: 'Open the dashboard and start from a ready template.' },
      { n: '2', t: 'Add your content', d: 'Upload projects, images and articles, arrange sections.' },
      { n: '3', t: 'Publish', d: 'Connect your domain and share with the world.' },
    ],
    showcaseTitle: 'Live portfolios on the platform',
    showcaseEmpty: 'Coming soon — the first portfolios are on the way.',
    visit: 'Visit',
    pricingTitle: 'Simple pricing',
    plans: [
      { name: 'Free', price: '0', per: 'forever', feats: ['One portfolio', 'ViralPX link', 'Projects & articles', '1GB storage'], cta: 'Start free', hi: false },
      { name: 'Pro', price: '199', per: '/mo', feats: ['Your own domain + SSL', 'More storage', 'Remove branding', 'Priority support'], cta: 'Go Pro', hi: true },
    ],
    faqTitle: 'Frequently asked',
    faqs: [
      { q: 'Do I need to code?', a: 'Not at all. Everything is drag-and-drop from the dashboard.' },
      { q: 'Can I use my own domain?', a: 'Yes — the Pro plan connects your domain with automatic SSL.' },
      { q: 'Is it bilingual?', a: 'Yes, Arabic & English with full right-to-left support.' },
      { q: 'Is my data isolated?', a: 'Every tenant is fully isolated, and media is served from a secure CDN.' },
    ],
    ctaTitle: 'Ready to launch your portfolio?',
    ctaSub: 'Start now — your first portfolio is free.',
    ctaBtn: 'Get started',
    rights: 'All rights reserved',
  },
}
