/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tenants: Tenant;
    media: Media;
    projects: Project;
    articles: Article;
    logos: Logo;
    testimonials: Testimonial;
    achievements: Achievement;
    visits: Visit;
    'site-settings': SiteSetting;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    logos: LogosSelect<false> | LogosSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    achievements: AchievementsSelect<false> | AchievementsSelect<true>;
    visits: VisitsSelect<false> | VisitsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'en') | ('ar' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Owner can manage every tenant. Regular clients are scoped to their own tenant.
   */
  isOwner?: boolean | null;
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Public portfolio lives at /<slug>. Must not be a reserved path.
   */
  slug: string;
  /**
   * Optional custom domain that resolves to this portfolio.
   */
  domain?: string | null;
  storageLimitMb?: number | null;
  storageUsedMb?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * One of the tenant’s image/video categories.
   */
  category?: string | null;
  description?: string | null;
  mediaType: 'image' | 'video';
  /**
   * How the detail page renders.
   */
  projectType: 'grid' | 'free' | 'stacked';
  /**
   * Cover / thumbnail (uses the generated thumb on grids).
   */
  cover?: (number | null) | Media;
  /**
   * Embed link (YouTube / Vimeo / direct).
   */
  videoUrl?: string | null;
  videoKind?: ('reel' | 'video') | null;
  aspectRatio?: string | null;
  /**
   * Gallery images (separate from the page-builder).
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Behance-style page builder (used by the "free" layout).
   */
  modules?:
    | (
        | {
            textType?: ('h1' | 'h2' | 'p') | null;
            value: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            src: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            items?:
              | {
                  src: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'grid';
          }
        | {
            items?:
              | {
                  src: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carousel';
          }
        | {
            /**
             * YouTube / Vimeo / direct embed URL.
             */
            embedUrl: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            before: number | Media;
            after: number | Media;
            labelBefore?: string | null;
            labelAfter?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'beforeafter';
          }
        | {
            /**
             * Thin gradient divider — pick the vertical spacing.
             */
            spacing?: ('compact' | 'normal' | 'large') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'separator';
          }
      )[]
    | null;
  /**
   * Uncheck to hide this project from the public portfolio (draft).
   */
  published?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * Auto from title; unique per tenant.
   */
  slug: string;
  excerpt?: string | null;
  cover?: (number | null) | Media;
  mode?: ('richtext' | 'html') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentHtml?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  /**
   * Estimated read time (minutes).
   */
  readMin?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos".
 */
export interface Logo {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  logo: number | Media;
  websiteUrl?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  tenant?: (number | null) | Tenant;
  name: string;
  role?: string | null;
  company?: string | null;
  content: string;
  avatar?: (number | null) | Media;
  rating?: number | null;
  source?: ('admin' | 'public') | null;
  approved?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * e.g. "50+"
   */
  value: string;
  icon?: (number | null) | Media;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visits".
 */
export interface Visit {
  id: number;
  tenant?: (number | null) | Tenant;
  visitorId?: string | null;
  page?: string | null;
  project?: (number | null) | Project;
  country?: string | null;
  device?: ('desktop' | 'mobile' | 'tablet') | null;
  referrer?: string | null;
  visitedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Internal label for this settings record.
   */
  siteName?: string | null;
  social?: {
    whatsapp?: string | null;
    behance?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    facebook?: string | null;
    vimeo?: string | null;
    visible?: ('whatsapp' | 'behance' | 'instagram' | 'linkedin' | 'facebook' | 'vimeo')[] | null;
  };
  brand?: {
    photo?: (number | null) | Media;
    avatar?: (number | null) | Media;
    heroCover?: (number | null) | Media;
    brandLogo?: (number | null) | Media;
    favicon?: (number | null) | Media;
    brandLogoScale?: number | null;
    brandLogoOffsetX?: number | null;
    brandLogoOffsetY?: number | null;
  };
  heroCover?: {
    /**
     * 'cover' | 'contain' | 'NN%'
     */
    size?: string | null;
    posX?: number | null;
    posY?: number | null;
    overlay?: number | null;
    /**
     * vh
     */
    height?: number | null;
  };
  colors?: {
    accent?: string | null;
    bg?: string | null;
    bg2?: string | null;
    text?: string | null;
    subtext?: string | null;
  };
  background?: {
    preset?: ('dark' | 'ocean' | 'sunset' | 'forest' | 'mono' | 'pearl') | null;
    type?: ('solid' | 'gradient') | null;
    color1?: string | null;
    color2?: string | null;
  };
  style?: {
    theme?: ('default' | 'kinetic') | null;
    hero?: ('centered' | 'split' | 'massive' | 'cover-full' | 'minimal') | null;
    about?: ('classic' | 'visual' | 'simple') | null;
    projects?: ('grid' | 'masonry' | 'list' | 'freegrid') | null;
    expertise?: ('grid' | 'stack') | null;
    contact?: ('classic' | 'split') | null;
    skills?: ('tags' | 'inline' | 'bars') | null;
    tools?: ('classic' | 'compact') | null;
    exp?: ('classic' | 'timeline') | null;
    font?: ('default' | 'modern' | 'editorial' | 'elegant' | 'bold') | null;
    direction?: ('auto' | 'rtl' | 'ltr') | null;
    cursor?: ('default' | 'dot-ring') | null;
    anim?: ('fade-up' | 'fade' | 'none') | null;
  };
  themeConfig?: {
    components?: {
      card?: ('solid' | 'glass' | 'outline') | null;
      navbar?: ('blur' | 'solid' | 'transparent') | null;
      button?: ('rounded' | 'sharp' | 'pill') | null;
    };
    tokens?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  footer?: {
    logoSize?: number | null;
    logoAlign?: string | null;
    socialsAlign?: string | null;
    copyAlign?: string | null;
  };
  /**
   * Per-theme override snapshots + _custom_<key> flags.
   */
  themeOverrides?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  gridCols?: {
    imageMobile?: number | null;
    imageTablet?: number | null;
    imageDesktop?: number | null;
    videoMobile?: number | null;
    videoTablet?: number | null;
    videoDesktop?: number | null;
    freegridMobile?: number | null;
    freegridDesktop?: number | null;
  };
  categories?: {
    image?:
      | {
          name?: string | null;
          id?: string | null;
        }[]
      | null;
    video?:
      | {
          name?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  projTabs?: {
    designs?: {
      visible?: boolean | null;
      label?: string | null;
      icon?: string | null;
    };
    reels?: {
      visible?: boolean | null;
      label?: string | null;
      icon?: string | null;
    };
    videos?: {
      visible?: boolean | null;
      label?: string | null;
      icon?: string | null;
    };
  };
  /**
   * Top-nav links (Articles link is appended automatically).
   */
  navbarLinks?:
    | {
        linkId: string;
        label?: string | null;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Portfolio sections — order + visibility (drag to reorder).
   */
  sections?:
    | {
        sectionId:
          | 'hero'
          | 'about'
          | 'projects'
          | 'achievements'
          | 'expertise'
          | 'testimonials'
          | 'logos'
          | 'experience'
          | 'tools'
          | 'education'
          | 'skills'
          | 'contact';
        label?: string | null;
        visible?: boolean | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  mobileBar?: {
    enabled?: boolean | null;
    buttons?:
      | {
          pos?: ('left' | 'center' | 'right') | null;
          type?: ('section' | 'whatsapp' | 'articles' | 'link') | null;
          target?: string | null;
          icon?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Instagram-style story circles above the projects grid.
   */
  highlights?:
    | {
        title?: string | null;
        cover?: (number | null) | Media;
        items?:
          | {
              type?: ('image' | 'video') | null;
              media: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  content?: {
    hero?: {
      name?: string | null;
      title?: string | null;
      btn1?: string | null;
      btn2?: string | null;
    };
    about?: {
      text?: string | null;
      /**
       * Comma-separated.
       */
      tags?: string | null;
    };
    expertise?: {
      title?: string | null;
      items?:
        | {
            title?: string | null;
            description?: string | null;
            icon?: (number | null) | Media;
            image?: (number | null) | Media;
            /**
             * Zoom %
             */
            bgZoom?: number | null;
            /**
             * Dim %
             */
            bgOverlay?: number | null;
            bgPosX?: number | null;
            bgPosY?: number | null;
            id?: string | null;
          }[]
        | null;
    };
    experience?: {
      items?:
        | {
            company?: string | null;
            role?: string | null;
            period?: string | null;
            description?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    education?: {
      items?:
        | {
            title?: string | null;
            org?: string | null;
            period?: string | null;
            description?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    skills?: {
      /**
       * Comma-separated.
       */
      items?: string | null;
    };
    tools?: {
      items?:
        | {
            name?: string | null;
            icon?: (number | null) | Media;
            id?: string | null;
          }[]
        | null;
    };
    projects?: {
      title?: string | null;
      subtitle?: string | null;
    };
    contact?: {
      title?: string | null;
      subtitle?: string | null;
      email?: string | null;
      phone?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'logos';
        value: number | Logo;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'achievements';
        value: number | Achievement;
      } | null)
    | ({
        relationTo: 'visits';
        value: number | Visit;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  isOwner?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  storageLimitMb?: T;
  storageUsedMb?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  category?: T;
  description?: T;
  mediaType?: T;
  projectType?: T;
  cover?: T;
  videoUrl?: T;
  videoKind?: T;
  aspectRatio?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  modules?:
    | T
    | {
        text?:
          | T
          | {
              textType?: T;
              value?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              src?: T;
              id?: T;
              blockName?: T;
            };
        grid?:
          | T
          | {
              items?:
                | T
                | {
                    src?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        carousel?:
          | T
          | {
              items?:
                | T
                | {
                    src?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              embedUrl?: T;
              id?: T;
              blockName?: T;
            };
        beforeafter?:
          | T
          | {
              before?: T;
              after?: T;
              labelBefore?: T;
              labelAfter?: T;
              id?: T;
              blockName?: T;
            };
        separator?:
          | T
          | {
              spacing?: T;
              id?: T;
              blockName?: T;
            };
      };
  published?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  cover?: T;
  mode?: T;
  content?: T;
  contentHtml?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  published?: T;
  readMin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos_select".
 */
export interface LogosSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  logo?: T;
  websiteUrl?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  role?: T;
  company?: T;
  content?: T;
  avatar?: T;
  rating?: T;
  source?: T;
  approved?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  value?: T;
  icon?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visits_select".
 */
export interface VisitsSelect<T extends boolean = true> {
  tenant?: T;
  visitorId?: T;
  page?: T;
  project?: T;
  country?: T;
  device?: T;
  referrer?: T;
  visitedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  siteName?: T;
  social?:
    | T
    | {
        whatsapp?: T;
        behance?: T;
        instagram?: T;
        linkedin?: T;
        facebook?: T;
        vimeo?: T;
        visible?: T;
      };
  brand?:
    | T
    | {
        photo?: T;
        avatar?: T;
        heroCover?: T;
        brandLogo?: T;
        favicon?: T;
        brandLogoScale?: T;
        brandLogoOffsetX?: T;
        brandLogoOffsetY?: T;
      };
  heroCover?:
    | T
    | {
        size?: T;
        posX?: T;
        posY?: T;
        overlay?: T;
        height?: T;
      };
  colors?:
    | T
    | {
        accent?: T;
        bg?: T;
        bg2?: T;
        text?: T;
        subtext?: T;
      };
  background?:
    | T
    | {
        preset?: T;
        type?: T;
        color1?: T;
        color2?: T;
      };
  style?:
    | T
    | {
        theme?: T;
        hero?: T;
        about?: T;
        projects?: T;
        expertise?: T;
        contact?: T;
        skills?: T;
        tools?: T;
        exp?: T;
        font?: T;
        direction?: T;
        cursor?: T;
        anim?: T;
      };
  themeConfig?:
    | T
    | {
        components?:
          | T
          | {
              card?: T;
              navbar?: T;
              button?: T;
            };
        tokens?: T;
      };
  footer?:
    | T
    | {
        logoSize?: T;
        logoAlign?: T;
        socialsAlign?: T;
        copyAlign?: T;
      };
  themeOverrides?: T;
  gridCols?:
    | T
    | {
        imageMobile?: T;
        imageTablet?: T;
        imageDesktop?: T;
        videoMobile?: T;
        videoTablet?: T;
        videoDesktop?: T;
        freegridMobile?: T;
        freegridDesktop?: T;
      };
  categories?:
    | T
    | {
        image?:
          | T
          | {
              name?: T;
              id?: T;
            };
        video?:
          | T
          | {
              name?: T;
              id?: T;
            };
      };
  projTabs?:
    | T
    | {
        designs?:
          | T
          | {
              visible?: T;
              label?: T;
              icon?: T;
            };
        reels?:
          | T
          | {
              visible?: T;
              label?: T;
              icon?: T;
            };
        videos?:
          | T
          | {
              visible?: T;
              label?: T;
              icon?: T;
            };
      };
  navbarLinks?:
    | T
    | {
        linkId?: T;
        label?: T;
        visible?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        sectionId?: T;
        label?: T;
        visible?: T;
        order?: T;
        id?: T;
      };
  mobileBar?:
    | T
    | {
        enabled?: T;
        buttons?:
          | T
          | {
              pos?: T;
              type?: T;
              target?: T;
              icon?: T;
              label?: T;
              id?: T;
            };
      };
  highlights?:
    | T
    | {
        title?: T;
        cover?: T;
        items?:
          | T
          | {
              type?: T;
              media?: T;
              id?: T;
            };
        id?: T;
      };
  content?:
    | T
    | {
        hero?:
          | T
          | {
              name?: T;
              title?: T;
              btn1?: T;
              btn2?: T;
            };
        about?:
          | T
          | {
              text?: T;
              tags?: T;
            };
        expertise?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    image?: T;
                    bgZoom?: T;
                    bgOverlay?: T;
                    bgPosX?: T;
                    bgPosY?: T;
                    id?: T;
                  };
            };
        experience?:
          | T
          | {
              items?:
                | T
                | {
                    company?: T;
                    role?: T;
                    period?: T;
                    description?: T;
                    id?: T;
                  };
            };
        education?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    org?: T;
                    period?: T;
                    description?: T;
                    id?: T;
                  };
            };
        skills?:
          | T
          | {
              items?: T;
            };
        tools?:
          | T
          | {
              items?:
                | T
                | {
                    name?: T;
                    icon?: T;
                    id?: T;
                  };
            };
        projects?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              subtitle?: T;
              email?: T;
              phone?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}